### ISSUE TITLE
Add support for pods

### ISSUE THREAD

**Issue by estshy** [williamsbdev/ember-cli-auto-register#12]
Idea behind this extension is great, although is a pity that it can not work out of the box with pods structure. For now I basically copy and paste solution locally but it would be nice to have something more reusable.

```
Object.keys(require.entries)
    .filter(path => /repository$/.test(path))
    .forEach(path => {
      const module = require(path, null, null, true);
      const domain = path.match(/(?:\w+\/)+pods\/((\w+\/)+)/)[1].slice(0, -1);

      application.register(`repository:${domain}`, module['default']);
    });
```

**Comment by williamsbdev** [comment]
@estshy - I apologize for the late response. I've had some time to think about this request and do some research. There is an RFC for [module unification](https://github.com/emberjs/rfcs/blob/master/text/0143-module-unification.md). I would prefer to wait to support this until we figure out what is going to win. The current support for this module is for the default structure only and you are correct in that I do not current support pods.

I have heard that pods are somewhat "discouraged" so I don't want to support something will potentially be deprecated or is out of favor with the ember core team.

I would encourage you to extend in your app as you have already done to meet your needs.
