### ISSUE TITLE
Use require.entries rather than require._eak_seen

### ISSUE THREAD

**Issue by tim-evans** [williamsbdev/ember-cli-auto-register#2]
`entries` seems to be the more standard approach for require (from https://github.com/ember-cli/loader.js)

Also, it's non-private, which implies a stable API.

https://github.com/ember-cli/loader.js/blob/master/loader.js#L187

**Comment by williamsbdev** [comment]
Awesome! Thanks for this find. I will test this out tonight.

**Comment by williamsbdev** [comment]
@tim-evans Thanks for pointing this out. I was able to change to the "public" `entries` API and all the tests continued to pass. This was released with the 0.1.2 version and was changed in this [commit](https://github.com/williamsbdev/ember-cli-auto-register/commit/9732e5a8d59253fb49d326b59a221f9eb23904b3).
